export const mockRepositories = [
    {
        "id": 1,
        "name": "repositorio1",
        "description": "Descrição do repositório 1",
        "stargazers_count": 123,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo1",
        "default_branch": "main",
        "forks_count": "10",
    },
    {
        "id": 2,
        "name": "repositorio2",
        "description": "Descrição do repositório 2",
        "stargazers_count": 456,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo2",
        "default_branch": "main",
        "forks_count": "20",
    },
    {
        "id": 3,
        "name": "repositorio3",
        "description": "Descrição do repositório 3",
        "stargazers_count": 789,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo3",
        "default_branch": "main",
        "forks_count": "30",
    },
    {
        "id": 4,
        "name": "repositorio4",
        "description": "Descrição do repositório 4",
        "stargazers_count": 321,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo4",
        "default_branch": "main",
        "forks_count": "40",
    },
    {
        "id": 5,
        "name": "repositorio5",
        "description": "Descrição do repositório 5",
        "stargazers_count": 654,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo5",
        "default_branch": "main",
        "forks_count": "50",
    },
    {
        "id": 6,
        "name": "repositorio6",
        "description": "Descrição do repositório 6",
        "stargazers_count": 987,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo6",
        "default_branch": "main",
        "forks_count": "60",
    },
    {
        "id": 7,
        "name": "repositorio7",
        "description": "Descrição do repositório 7",
        "stargazers_count": 135,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo7",
        "default_branch": "main",
        "forks_count": "70",
    },
    {
        "id": 8,
        "name": "repositorio8",
        "description": "Descrição do repositório 8",
        "stargazers_count": 246,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo8",
        "default_branch": "main",
        "forks_count": "80",
    },
    {
        "id": 9,
        "name": "repositorio9",
        "description": "Descrição do repositório 9",
        "stargazers_count": 753,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo9",
        "default_branch": "main",
        "forks_count": "80",
    },
    {
        "id": 10,
        "name": "repositorio10",
        "description": "Descrição do repositório 10",
        "stargazers_count": 102,
        "language": "JavaScript",
        "html_url": "https://github.com/usuario/repo10",
        "default_branch": "main",
        "forks_count": "2100",
    }
];